services:
  - type: web
    name: yotam-portfolio
    env: static
    region: oregon
    plan: free
    branch: main
    rootDir: v4
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./public
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
