services:
  - type: web
    name: yotam-portfolio
    env: static
    region: oregon
    plan: free
    branch: main
    buildCommand: cd v4 && npm install --legacy-peer-deps && npm run build
    staticPublishPath: v4/public
    envVars:
      - key: NODE_VERSION
        value: 18.20.5
